name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Lint PHP files
      run: vendor/bin/phplint . --exclude=vendor -w

    - name: Checking for sign off (GPG also accepted)
      run: php ./check-signed-off.php

    - name: Checking file integrity
      run: |
        php ./check-eof.php
        php ./check-smf-license.php
        php ./check-smf-languages.php
        php ./check-version.php
